### ISSUE TITLE
Minecraft crash after WeCui install

### ISSUE THREAD

**Issue by harmo** [yetanotherx/WorldEditCUI#8]
Hello,

I used this awsome mod on minecraft 1.1, but since updated to 1.2.3, my game crash after the white screen...
Here is the modloader log :

mars 09, 2012 2:44:26 PM ModLoader init
Précis: ModLoader 1.2.3 Initializing...
mars 09, 2012 2:44:26 PM ModLoader readFromClassPath
Plus précis: Adding mods from /home/harmo/.minecraft/bin/minecraft.jar
mars 09, 2012 2:44:26 PM ModLoader readFromClassPath
Plus précis: Zip found.
mars 09, 2012 2:44:26 PM ModLoader addMod
Précis: Failed to load mod from "mod_WorldEditCUI.class"
mars 09, 2012 2:44:26 PM ModLoader addMod
Plus précis: THROW
java.lang.NoClassDefFoundError: wecui/render/RenderEntity
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2308)
    at java.lang.Class.getDeclaredFields(Class.java:1760)
    at ModLoader.setupProperties(ModLoader.java:1720)
    at ModLoader.addMod(ModLoader.java:292)
    at ModLoader.readFromClassPath(ModLoader.java:1217)
    at ModLoader.init(ModLoader.java:885)
    at ModLoader.addAllRenderers(ModLoader.java:186)
    at aho.<init>(aho.java:79)
    at aho.<clinit>(aho.java:9)
    at net.minecraft.client.Minecraft.a(SourceFile:267)
    at net.minecraft.client.Minecraft.run(SourceFile:650)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: wecui.render.RenderEntity
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 13 more

mars 09, 2012 2:44:36 PM ModLoader addAllRenderers
Précis: Initialized

**Comment by ghost** [comment]
I am guessing you didn't copy all the files into the jar properly. Try another method such as extracting all files into a tmp folder, copying the mod files into there and then compressing the contents of that folder back into a jar file.

Here is what I used to make it work inside my temp folder after I extracted all the files, removed the META-INF folder and copied the modloader and WorldEditCUI mod into the folder on Linux:
jar uf ~/.minecraft/bin/minecraft.jar ./
